<script setup>
import {ref,computed,onMounted} from 'vue';
const rows=ref([]), error=ref(''), busy=ref(false), category=ref('All');
const blank=()=>{const now=new Date();const date=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');return {id:0,description:'',category:'Other',amount:'',spent_on:date};};
const draft=ref(blank());
const visible=computed(()=>rows.value.filter(r=>category.value==='All'||r.category===category.value));
const total=computed(()=>visible.value.reduce((sum,r)=>sum+r.amount_cents,0));
const money=cents=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(cents/100);
async function request(path,method='GET',body){const r=await fetch(path,{method,headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:body?JSON.stringify(body):undefined});if(!r.ok){const data=await r.json().catch(()=>({}));throw new Error(Object.values(data.errors||{}).flat().join(' ')||data.message||'Request failed.');}return r.status===204?null:r.json();}
async function load(){rows.value=await request('/expenses');}
async function save(){busy.value=true;error.value='';try{if(!/^\d+(\.\d{1,2})?$/.test(draft.value.amount))throw new Error('Enter a positive amount with at most two decimals.');const cents=Math.round(Number(draft.value.amount)*100);const {id,amount,...rest}=draft.value;await request('/expenses'+(id?'/'+id:''),id?'PUT':'POST',{...rest,amount_cents:cents});draft.value=blank();await load();}catch(e){error.value=e.message;}finally{busy.value=false;}}
function edit(row){draft.value={...row,amount:(row.amount_cents/100).toFixed(2)};}
async function remove(row){if(!confirm('Delete this expense?'))return;busy.value=true;try{await request('/expenses/'+row.id,'DELETE');if(draft.value.id===row.id)draft.value=blank();await load();}catch(e){error.value=e.message;}finally{busy.value=false;}}
onMounted(async()=>{try{await load();}catch(e){error.value=e.message;}});
</script>
<template><main><header><div><span class="eyebrow">Sachibara / Laravel + VueJS</span><h1>Expense Atlas</h1><p class="muted">Track the cost of keeping your work moving.</p></div><span class="badge">PHP · SQLite · Vue</span></header><p v-if="error" class="error" role="alert">{{error}}</p><div class="grid"><div class="card"><span class="muted">Filtered spending</span><div class="stat">{{money(total)}}</div></div><div class="card"><span class="muted">Records</span><div class="stat">{{visible.length}}</div></div><div class="card"><span class="muted">Currency</span><div class="stat">PHP</div></div></div>
<form class="inline" @submit.prevent="save"><label>Description<br><input required maxlength="120" v-model="draft.description"></label><label>Amount (PHP)<br><input required inputmode="decimal" v-model="draft.amount" placeholder="125.50"></label><label>Category<br><select v-model="draft.category"><option>Travel</option><option>Equipment</option><option>Software</option><option>Other</option></select></label><label>Date<br><input type="date" required v-model="draft.spent_on"></label><button :disabled="busy">{{draft.id?'Update':'Add expense'}}</button><button type="button" class="secondary" @click="draft=blank()">Cancel</button></form>
<div class="toolbar"><label>Category filter<br><select v-model="category"><option>All</option><option>Travel</option><option>Equipment</option><option>Software</option><option>Other</option></select></label></div><section class="panel table-wrap"><table><thead><tr><th>Description</th><th>Category</th><th>Date</th><th>Amount</th><th>Actions</th></tr></thead><tbody><tr v-for="r in visible" :key="r.id"><td>{{r.description}}</td><td>{{r.category}}</td><td>{{r.spent_on}}</td><td>{{money(r.amount_cents)}}</td><td><button class="secondary" :disabled="busy" @click="edit(r)">Edit</button> <button class="danger" :disabled="busy" @click="remove(r)">Delete</button></td></tr></tbody></table><p v-if="!visible.length">No expenses in this category.</p></section><footer>Local portfolio demo · Amounts stored as integer centavos · Laravel web CSRF protection</footer></main></template>
