const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date().toISOString();
const sampleLogs=()=>Array.from({length:6},(_,i)=>JSON.stringify({timestamp:`2026-10-04T12:0${i}:00Z`,ip:'192.0.2.10',user:'demo',event:i===5?'login_success':'login_failed'})).join('\n');
const tools=[
{id:'network',name:'Network planner',description:'Allocate non-overlapping VLAN subnets and generate a reviewable configuration.',route:'/api/network/plan',fields:[['network','Parent IPv4 network','input'],['vlans','VLAN requirements (JSON)','textarea']],sample:()=>({network:'10.20.0.0/24',vlans:JSON.stringify([{id:10,name:'Staff',hosts:50},{id:20,name:'Guests',hosts:25},{id:30,name:'Servers',hosts:10}],null,2)}),parse:v=>({...v,vlans:JSON.parse(v.vlans)})},
{id:'config',name:'Configuration audit',description:'Compare device configurations and check a small Cisco IOS baseline.',route:'/api/config/audit',fields:[['baseline','Baseline configuration','textarea'],['candidate','Candidate configuration','textarea']],sample:()=>({baseline:'hostname HQ\nip ssh version 2\naaa new-model\nservice timestamps log datetime msec\nlogging host 10.0.0.10\ntransport input ssh',candidate:'hostname HQ\nip ssh version 2\ntransport input telnet\nusername admin secret demo-only'})},
{id:'security',name:'Security log triage',description:'Find repeated authentication failures and subsequent successful logins.',route:'/api/security/analyze',fields:[['logs','Authentication events (JSON Lines)','textarea']],sample:()=>({logs:sampleLogs()})},
{id:'endpoint',name:'Endpoint baseline',description:'Review reported firewall state, disk space and inventory freshness.',route:'/api/endpoints/check',fields:[['devices','Device inventory (JSON array)','textarea']],sample:()=>({devices:JSON.stringify([{name:'LAPTOP-001',os:'Windows 11',disk_free_percent:42,firewall_enabled:true,observed_at:now()},{name:'LAPTOP-002',os:'Windows 11',disk_free_percent:8,firewall_enabled:false,observed_at:now()}],null,2)}),parse:v=>({devices:JSON.parse(v.devices)})},
{id:'data',name:'Data pipeline & BI',description:'Validate ticket CSVs, upsert records and calculate resolution/SLA reports.',route:'/api/data/import',fields:[['csv','Ticket data (CSV)','textarea']],sample:()=>({csv:'id,priority,opened_at,resolved_at\nDEMO-1,P1,2026-10-01T08:00:00Z,2026-10-01T10:00:00Z\nDEMO-2,P1,2026-10-01T08:00:00Z,2026-10-01T14:00:00Z\nDEMO-3,P2,2026-10-01T08:00:00Z,2026-10-01T15:00:00Z\nDEMO-4,P3,2026-10-01T08:00:00Z,'})},
{id:'documents',name:'Knowledge sources',description:'Add technical source documents for citation-backed retrieval.',route:'/api/documents/add',fields:[['title','Document title','input'],['body','Source text','textarea']],sample:()=>({title:'DNS troubleshooting runbook',body:'To investigate DNS resolution failures, first confirm IP connectivity to the configured resolver. Compare nslookup results with the expected internal record. Verify the client DNS server configuration. Flush a stale client cache only after validating the authoritative record. Escalate persistent resolver failures with timestamps and query output.'})},
{id:'knowledge',name:'Knowledge assistant',description:'Retrieve source excerpts or request a local-model answer through Ollama.',route:'/api/knowledge/ask',fields:[['question','Question','input'],['use_model','Use configured local model','checkbox']],sample:()=>({question:'How do I investigate DNS resolution failures?',use_model:false})},
{id:'monitor',name:'Service monitor',description:'Check the HTTP services configured by the workspace operator.',route:'/api/monitor/check',fields:[],sample:()=>({})}
];let active=tools[0],result=null;
function renderFields(){ $('title').textContent=active.name;$('subtitle').textContent=active.description;$('fields').innerHTML=active.fields.map(([id,label,type])=>`<label for="field-${id}">${esc(label)}</label>${type==='textarea'?`<textarea id="field-${id}" required></textarea>`:`<input id="field-${id}" type="${type==='checkbox'?'checkbox':'text'}" ${type!=='checkbox'?'required':''}>`}`).join('');$('result').innerHTML='<div class="empty"><div class="empty-icon">↗</div><h3>Ready when you are</h3><p>Load an example or enter your data, then run the tool.</p></div>';$('upload').parentElement.hidden=!active.fields.some(f=>f[2]==='textarea');result=null;$('export').disabled=true;$('error').hidden=true;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.id===active.id));}
$('nav').innerHTML=tools.map(t=>`<button data-id="${t.id}">${t.name}</button>`).join('');$('nav').addEventListener('click',e=>{const id=e.target.closest('button')?.dataset.id;if(id){active=tools.find(t=>t.id===id);renderFields();}});
function fail(error){$('error').textContent=error.message||String(error);$('error').hidden=false;}
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:'Bearer '+$('token').value},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
try{$('token').value=sessionStorage.getItem('ops-token')||'';}catch{}
$('connect').onclick=async()=>{try{await api('/api/history');try{sessionStorage.setItem('ops-token',$('token').value);}catch{}$('connection').textContent='Connected';$('error').hidden=true;}catch(e){$('connection').textContent='Not connected';fail(e);}};
$('sample').onclick=()=>{const value=active.sample();for(const [id,,type] of active.fields){if(type==='checkbox')$('field-'+id).checked=!!value[id];else $('field-'+id).value=value[id]??'';}};
$('upload').onchange=async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>1000000)throw Error('File must be under 1 MB.');const field=active.fields.find(f=>f[2]==='textarea');if(field)$('field-'+field[0]).value=(await file.text()).replace(/^\uFEFF/,'');}catch(e){fail(e);}finally{e.target.value='';}};
function table(rows,columns){return '<div class="table-wrap"><table><thead><tr>'+columns.map(([key,label])=>'<th>'+esc(label)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+columns.map(([key])=>'<td>'+esc(Array.isArray(row[key])?row[key].join(', '):row[key])+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function stats(values){return '<div class="stats">'+values.map(([name,value])=>`<div class="stat">${esc(name)}<strong>${esc(value)}</strong></div>`).join('')+'</div>';}
function show(data,id){let html='';
if(id==='network')html=stats([['VLANs',data.vlans.length],['Addresses allocated',data.allocated_addresses]])+table(data.vlans,[['name','Name'],['vlan','VLAN'],['network','Subnet'],['gateway','Gateway'],['client_start','First client'],['client_end','Last client']])+`<pre>${esc(data.configuration)}</pre><p class="note">${esc(data.configuration_note)}</p>`;
if(id==='config')html=stats([['Passed',data.passed],['Checks',data.total]])+table(data.checks.map(c=>({...c,passed:c.passed?'Pass':'Review'})),[['rule','Rule'],['passed','Result']])+`<pre>${esc(data.diff||'No configuration changes.')}</pre>`;
if(id==='security')html=stats([['Valid events',data.events],['Alerts',data.alerts.length],['Rejected',data.rejected.length]])+table(data.alerts,[['severity','Severity'],['rule','Finding'],['ip','Source IP'],['timestamp','Time']])+table(data.rejected,[['line','Rejected line'],['error','Reason']]);
if(id==='endpoint')html=stats([['Devices',data.total],['Need review',data.review]])+table(data.devices,[['name','Device'],['disk_free_percent','Free disk %'],['status','Status'],['issues','Findings']]);
if(id==='data'){const s=data.summary;html=stats([['Accepted',data.accepted],['Rejected',data.rejected.length],['Stored',s.total]])+table(s.groups,[['priority','Priority'],['total','Tickets'],['open','Open'],['average_resolution_hours','Mean hours'],['sla_percent','SLA met %']])+s.groups.map(g=>`<div class="bar-row"><span>${g.priority}</span><progress max="100" value="${g.sla_percent||0}" aria-label="${g.priority} SLA percentage"></progress><span>${g.sla_percent??'—'}%</span></div>`).join('')+`<p class="note">${esc(s.definition)}</p>`+table(data.rejected,[['line','Rejected line'],['error','Reason']]);}
if(id==='documents')html=`<div class="source"><strong>Document ${data.id} saved</strong><p>${esc(data.title)}</p><p>Open Knowledge assistant to search this document.</p></div>`;
if(id==='knowledge')html=`<span class="tag">${esc(data.mode)}</span><pre>${esc(data.answer)}</pre>`+data.sources.map(s=>`<div class="source"><strong>[${s.id}] ${esc(s.title)}</strong><p>${esc(s.excerpt)}</p></div>`).join('');
if(id==='monitor')html=table(data.targets.map(t=>({...t,state:t.up?'Up':'Down'})),[['name','Service'],['state','State'],['latency_ms','Latency ms'],['status','HTTP'],['error','Error']]);
if(data.note)html+=`<p class="note">${esc(data.note)}</p>`;$('result').innerHTML=html;
}
$('tool-form').onsubmit=async e=>{e.preventDefault();const selected=active;const payload={};for(const [id,,type] of selected.fields)payload[id]=type==='checkbox'?$('field-'+id).checked:$('field-'+id).value;$('run').disabled=true;$('run').textContent='Working…';$('error').hidden=true;try{const data=await api(selected.route,selected.parse?selected.parse(payload):payload);if(active.id===selected.id){result=data;show(data,selected.id);$('export').disabled=false;}}catch(error){fail(error);}finally{$('run').disabled=false;$('run').textContent='Run analysis';}};
$('export').onclick=()=>{if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=active.id+'-report.json';a.click();URL.revokeObjectURL(url);};renderFields();
