'use client';
import {useState,type FormEvent} from 'react';import {useRouter} from 'next/navigation';
type Row={id:string;title:string;priority:string;status:string};type User={email:string;role:string};
export default function Portal({user,rows,initialError}:{user:User|null;rows:Row[];initialError:string}){
 const router=useRouter();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[title,setTitle]=useState(''),[error,setError]=useState(initialError),[busy,setBusy]=useState(false),[signup,setSignup]=useState(false);
 async function post(path:string,body:unknown){const response=await fetch('/api'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(user){await post('/incidents',{title,priority:'Medium',status:'New'});setTitle('');}else{if(signup)await post('/auth/register',{email,password});await post('/auth/login',{email,password});setPassword('');}router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main><header><div><span className="eyebrow">Sachibara / Next.js App Router</span><h1>Operations portal</h1><p className="muted">{user?user.email+' · '+user.role:'Secure session cookies and server-rendered incident data.'}</p></div>{user&&<button className="secondary" onClick={async()=>{try{await post('/auth/logout',{});router.refresh();}catch(e){setError((e as Error).message);}}}>Sign out</button>}</header>{error&&<p role="alert" className="error">{error}</p>}<section className="panel"><form className="inline" onSubmit={submit}>{user?<label>Incident title<br/><input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={120}/></label>:<><label>Email<br/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<br/><input type="password" minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/></label></>}<button disabled={busy}>{user?'Create incident':signup?'Create account':'Sign in'}</button>{!user&&<button type="button" className="secondary" onClick={()=>setSignup(!signup)}>{signup?'Use existing account':'Register'}</button>}</form></section>{user&&<><div className="toolbar"><button className="secondary" onClick={()=>router.refresh()}>Refresh server data</button></div><section className="grid">{rows.map(row=><article className="card" key={row.id}><span className="badge">{row.priority} · {row.status}</span><h2>{row.title}</h2></article>)}</section>{!rows.length&&<p>No incidents yet.</p>}</>}<footer>The full React workspace supports editing and audit history. This companion portal demonstrates server rendering and an HttpOnly session boundary.</footer></main>;
}
