import {test,expect} from 'playwright/test';
test.beforeEach(async({page})=>{await page.goto('/');await page.getByLabel('Operator token').fill('qa-only-token-do-not-deploy');await page.getByRole('button',{name:'Connect',exact:true}).click();await expect(page.locator('#connection')).toHaveText('Connected');});
async function sample(page:any,name:string){await page.getByRole('button',{name,exact:true}).click();await page.getByRole('button',{name:'Load example'}).click();await page.getByRole('button',{name:'Run analysis'}).click();}
test('network planning renders real allocation and rejects overflow',async({page})=>{await sample(page,'Network planner');await expect(page.locator('#result')).toContainText('10.20.0.0/26');await expect(page.getByRole('button',{name:'Export JSON'})).toBeEnabled();await page.getByLabel('Parent IPv4 network').fill('10.20.0.0/30');await page.getByRole('button',{name:'Run analysis'}).click();await expect(page.getByRole('alert')).toContainText('do not fit');});
test('configuration secrets are redacted',async({page})=>{await sample(page,'Configuration audit');await expect(page.locator('#result')).toContainText('REDACTED');await expect(page.locator('#result')).not.toContainText('demo-only');});
test('security and endpoint findings render',async({page})=>{await sample(page,'Security log triage');await expect(page.locator('#result')).toContainText('Success after repeated failures');await sample(page,'Endpoint baseline');await expect(page.locator('#result')).toContainText('LAPTOP-002');await expect(page.locator('#result')).toContainText('Free system disk below 15%');});
test('CSV import produces SLA report and is idempotent',async({page})=>{await sample(page,'Data pipeline & BI');await expect(page.locator('#result')).toContainText('50%');const stats=page.locator('#result .stat');await expect(stats.nth(2)).toContainText('4');await page.getByRole('button',{name:'Run analysis'}).click();await expect(stats.nth(2)).toContainText('4');});
test('source document is retrieved with a citation',async({page})=>{await sample(page,'Knowledge sources');await expect(page.locator('#result')).toContainText('saved');await sample(page,'Knowledge assistant');await expect(page.locator('#result')).toContainText('DNS troubleshooting runbook');await expect(page.locator('#result')).toContainText('retrieval');});
test('monitor checks actual HTTP service',async({page})=>{await sample(page,'Service monitor');await expect(page.locator('#result')).toContainText('QA server');await expect(page.locator('#result')).toContainText('Up');});
test('mobile layout and safe rendering have no script errors',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:390,height:844});await sample(page,'Network planner');await expect(page.locator('#result')).toContainText('10.20.0.0/26');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(errors).toEqual([]);});
