import React,{useEffect,useState} from 'react';
import {SafeAreaView,ScrollView,View,Text,TextInput,Pressable,StyleSheet,Alert,ActivityIndicator} from 'react-native';
import * as SecureStore from 'expo-secure-store';
type Incident={id:string;title:string;priority:string;status:string;version:number};
const endpoint=process.env.EXPO_PUBLIC_API_URL||'';
export default function App(){
 const [token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[rows,setRows]=useState<Incident[]>([]),[title,setTitle]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function request(path:string,method='GET',body?:unknown,auth=token){if(!endpoint)throw Error('Configure EXPO_PUBLIC_API_URL before starting Expo.');const response=await fetch(endpoint.replace(/\/$/,'')+'/api'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+auth},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}
 async function refresh(auth=token){setRows((await request('/incidents','GET',undefined,auth)).incidents);}
 useEffect(()=>{SecureStore.getItemAsync('operations-token').then(async saved=>{if(saved){try{await refresh(saved);setToken(saved);}catch{await SecureStore.deleteItemAsync('operations-token');}}}).catch(e=>setError(e.message));},[]);
 async function work(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function login(){const data=await request('/auth/login','POST',{email,password});await SecureStore.setItemAsync('operations-token',data.token);setToken(data.token);setPassword('');await refresh(data.token);}
 async function create(){await request('/incidents','POST',{title,priority:'Medium',status:'New'});setTitle('');await refresh();}
 async function advance(row:Incident){const next=row.status==='New'?'Investigating':row.status==='Investigating'?'Resolved':'New';await request('/incidents/'+row.id,'PATCH',{...row,status:next});await refresh();}
 async function logout(){try{await request('/auth/logout','POST',{});}finally{await SecureStore.deleteItemAsync('operations-token');setToken('');setRows([]);}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><Text style={s.eyebrow}>SACHIBARA / MOBILE</Text><Text style={s.heading}>Service desk</Text><Text style={s.subtitle}>Your incidents, wherever work takes you.</Text>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{busy?<ActivityIndicator color="#385ce0"/>:null}
 {!token?<View style={s.card}><Text style={s.label}>Email</Text><TextInput accessibilityLabel="Email" style={s.input} value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><Text style={s.label}>Password</Text><TextInput accessibilityLabel="Password" style={s.input} secureTextEntry value={password} onChangeText={setPassword}/><Pressable accessibilityRole="button" disabled={busy} style={s.button} onPress={()=>void work(login)}><Text style={s.buttonText}>Sign in</Text></Pressable><Text style={s.small}>Create your operator account in the web application first.</Text></View>:<><View style={s.row}><Pressable accessibilityRole="button" onPress={()=>void work(()=>refresh())}><Text style={s.link}>Refresh</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>void work(logout)}><Text style={s.link}>Sign out</Text></Pressable></View><View style={s.card}><Text style={s.label}>New incident</Text><TextInput accessibilityLabel="Incident title" style={s.input} maxLength={120} value={title} onChangeText={setTitle} placeholder="Describe the issue"/><Pressable accessibilityRole="button" disabled={busy||!title.trim()} style={s.button} onPress={()=>void work(create)}><Text style={s.buttonText}>Create incident</Text></Pressable></View>{rows.map(row=><View key={row.id} style={s.card}><Text style={s.badge}>{row.priority} · {row.status}</Text><Text style={s.title}>{row.title}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>Alert.alert('Update status','Move this incident to the next state?',[{text:'Cancel',style:'cancel'},{text:'Update',onPress:()=>void work(()=>advance(row))}])}><Text style={s.link}>{row.status==='Resolved'?'Reopen':'Advance status'} →</Text></Pressable></View>)}{!rows.length?<Text style={s.subtitle}>No incidents yet.</Text>:null}</>}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f4f6fb'},page:{padding:24,paddingBottom:50},eyebrow:{fontSize:11,letterSpacing:2,color:'#6b7c99',marginTop:20},heading:{fontSize:38,fontWeight:'700',color:'#1a2d48',marginTop:12},subtitle:{color:'#6b7c99',lineHeight:22,marginVertical:16},card:{backgroundColor:'#fff',borderRadius:16,padding:20,marginBottom:16,borderWidth:1,borderColor:'#e0e7f3'},label:{fontSize:12,fontWeight:'600',color:'#52637e'},input:{borderWidth:1,borderColor:'#cbd6e8',borderRadius:8,padding:12,marginVertical:10,fontSize:16,color:'#192e49'},button:{backgroundColor:'#385ce0',borderRadius:8,padding:14,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'600'},small:{fontSize:12,color:'#6b7c99',lineHeight:20,marginTop:14},error:{backgroundColor:'#ffedf2',color:'#a02547',padding:12,marginBottom:14,borderRadius:8},row:{flexDirection:'row',justifyContent:'space-between',marginBottom:22},link:{color:'#385ce0',fontWeight:'600',paddingVertical:8},badge:{color:'#647895',fontSize:12},title:{fontSize:20,fontWeight:'600',color:'#1c304b',marginVertical:14}});
