import {useEffect,useState,type FormEvent} from 'react';import {createRoot} from 'react-dom/client';import './style.css';
type User={id:string;email:string;role:string};type Incident={id:string;title:string;priority:string;status:string;version:number};type Audit={action:string;target:string;created:string;email:string};
const blank=()=>({title:'',priority:'Medium',status:'New'});
function App(){
 const [token,setToken]=useState(()=>sessionStorage.getItem('operations-token')||'');const [user,setUser]=useState<User|null>(null);const [rows,setRows]=useState<Incident[]>([]);const [events,setEvents]=useState<Audit[]>([]);const [draft,setDraft]=useState(blank());const [editing,setEditing]=useState<Incident|null>(null);const [query,setQuery]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [register,setRegister]=useState(false);const [notice,setNotice]=useState('');
 async function api(path:string,method='GET',body?:unknown,version?:number,auth=token){const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+auth,...(version?{'If-Match':String(version)}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
 async function refresh(auth=token,role=user?.role){const data=await api('/incidents','GET',undefined,undefined,auth);setRows(data.incidents);if(role==='admin')setEvents((await api('/audit','GET',undefined,undefined,auth)).events);}
 useEffect(()=>{if(!token){setUser(null);return;}let cancelled=false;api('/auth/me').then(async data=>{if(!cancelled){setUser(data.user);await refresh(token,data.user.role);}}).catch(e=>{if(!cancelled){setError(e.message);setToken('');sessionStorage.removeItem('operations-token');}});return()=>{cancelled=true;};},[token]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const data=await api(register?'/auth/register':'/auth/login','POST',{email,password});if(register){setRegister(false);setNotice('Account created. Sign in to continue.');}else{sessionStorage.setItem('operations-token',data.token);setToken(data.token);setPassword('');setNotice('');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/incidents'+(editing?'/'+editing.id:''),editing?'PATCH':'POST',{...draft,...(editing?{version:editing.version}:{})});setDraft(blank());setEditing(null);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(row:Incident){if(!confirm('Delete this incident?'))return;setBusy(true);try{await api('/incidents/'+row.id,'DELETE',undefined,row.version);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){try{await api('/auth/logout','POST',{});}catch{}sessionStorage.removeItem('operations-token');setToken('');setUser(null);setRows([]);setEvents([]);}
 if(!user)return <main><span className="eyebrow">Sachibara / Fullstack platform</span><h1>Your operations, together.</h1><p className="muted">Account-based incident management with ownership controls and an audit trail.</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}<section className="panel"><h2>{register?'Create an operator account':'Sign in'}</h2><form className="stack" onSubmit={login}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" required minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={register?'new-password':'current-password'}/></label><button disabled={busy}>{register?'Register':'Sign in'}</button><button type="button" className="secondary" onClick={()=>setRegister(!register)}>{register?'Already have an account?':'Create account'}</button></form></section></main>;
 return <main><header><div><span className="eyebrow">Sachibara / Operations platform</span><h1>Incident workspace</h1><p className="muted">{user.email} · {user.role}</p></div><button className="secondary" onClick={()=>void logout()}>Sign out</button></header>{error&&<p className="error" role="alert">{error}</p>}<div className="grid">{['New','Investigating','Resolved'].map(s=><div className="card" key={s}>{s}<div className="stat">{rows.filter(r=>r.status===s).length}</div></div>)}</div><form className="inline" onSubmit={save}><label>Title<br/><input required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Priority<br/><select value={draft.priority} onChange={e=>setDraft({...draft,priority:e.target.value})}>{['High','Medium','Low'].map(s=><option key={s}>{s}</option>)}</select></label><label>Status<br/><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{['New','Investigating','Resolved'].map(s=><option key={s}>{s}</option>)}</select></label><button disabled={busy}>{editing?'Update incident':'Create incident'}</button><button type="button" className="secondary" onClick={()=>{setEditing(null);setDraft(blank());}}>Cancel</button></form><div className="toolbar"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)}/></label><button disabled={busy} onClick={()=>refresh().catch(e=>setError(e.message))}>Refresh</button></div><section className="grid">{rows.filter(r=>r.title.toLowerCase().includes(query.toLowerCase())).map(row=><article key={row.id} className="card"><span className="badge">{row.priority} · {row.status}</span><h2>{row.title}</h2><p className="muted">Version {row.version}</p><button className="secondary" disabled={busy} onClick={()=>{setEditing(row);setDraft({title:row.title,priority:row.priority,status:row.status});}}>Edit</button> <button className="danger" disabled={busy} onClick={()=>void remove(row)}>Delete</button></article>)}</section>{!rows.length&&<p>No incidents yet.</p>}{user.role==='admin'&&<section className="panel table-wrap"><h2>Audit trail</h2><table><thead><tr><th>When</th><th>Who</th><th>Action</th></tr></thead><tbody>{events.map((e,i)=><tr key={i}><td>{new Date(e.created).toLocaleString()}</td><td>{e.email}</td><td>{e.action}</td></tr>)}</tbody></table></section>}<footer>Operators see their own incidents; administrators see all. Updates reject stale versions.</footer></main>;
}createRoot(document.getElementById('root')!).render(<App/>);
